### ISSUE TITLE
Draconian race

### ISSUE THREAD

**Issue by mattias** [broquaint/soup-stash#4]
Since draconian's gets a colour at xl 7, the race changes to, for example, White Draconian. So when you check recent games for Draconian Transmuter or something similar, you only get the sub-xl 7 ones, not a single one above or at xl 7 which has a colour. I noticed this since my White Draconian wasn't seen here: http://soupstash.broquaint.com/games?background=Transmuter&race=Draconian

**Comment by broquaint** [comment]
Thanks for the bug report, it has pushed me to rework a crufty part of the code :)

This has now been fixed by 19759f7, will push it live later today, in the mean time you can see the behaviour on the development server which lives at the same address on port 3000.
