### ISSUE TITLE
error with morgues (giving a 404)

### ISSUE THREAD

**Issue by sepik121** [broquaint/soup-stash#7]
http://dobrazupa.org/morgue/sepik121/morgue-sepik121-20130806-154853.txt

This is my last morgue file. However, when I access it through soupstash, it leads to here: 

http://soupstash.broquaint.com/games/crawl-sepik121-DrWz-20130806154853

and links back to this morgue:

http://dobrazupa.org/morgue/sepik121/morgue-sepik121-20130806154853.txt

Which is missing the dash between 20130806 and 154853.

**Comment by broquaint** [comment]
Fixed a while back when I noticed it was broken. Sorry for not responding sooner, I must've missed the notification and haven't thought to check the outstanding issues. Thanks for the feedback!
